pipeline{
	agent any
	
	stages{
		stage('Check stage'){
			steps{
				withMaven(maven : 'Mvn'){
				bat 'mvn --version'
				}
			}
		}
	
		stage('Compile stage'){
			steps{
				withMaven(maven : 'Mvn'){
				bat 'mvn clean --version'
				}
			}
		}
		
		stage('Test stage'){
			steps{
				withMaven(maven : 'Mvn'){
				bat 'mvn test'
				}
			}
		}
	}


}