pipeline{
	agent any
	
	stages{
		stage('Check stage'){
			steps{
				withMaven(maven : 'Mvn'){
				bat 'mvn --version'
				}
			}
		}
		
		stage('Clean stage'){
			steps{
				withMaven(maven : 'Mvn'){
				bat 'mvn -f mvn-math/pom.xml clean'
				}
			}
		}
		
		stage('Compile stage'){
			steps{
				withMaven(maven : 'Mvn'){
				bat 'mvn -f mvn-math/pom.xml compile'
				}
			}
		}
		
		stage('Test stage'){
			steps{
				withMaven(maven : 'Mvn'){
				bat 'mvn -f mvn-math/pom.xml test'
				}
			}
		}
		
		
	}


}